name: Build Android Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Get Dependencies
        run: flutter pub get

      - name: Ensure Android V2 Embedding
        run: flutter config --enable-android

      - name: Build Release Universal APK
        run: flutter build apk --release --no-tree-shake-icons --no-split-per-abi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
